"""Orchestrator Agent Prompts"""

RECENT_NEWS_QUESTION = """Find urgent breaking news, developing stories, or just-announced events about {company_name} from the last week that could materially impact the company's stock price, business operations, or market position. Focus specifically on: SEC filings, earnings surprises, merger announcements, regulatory actions, executive changes, product launches, legal developments, partnership deals, or crisis events that financial news outlets, Bloomberg, Reuters, or business wire services would classify as urgent or market-moving."""

CONTEXT_NEWS_QUESTION = """Analyze current geopolitical developments and macroeconomic shifts that could impact {company_name}'s global business operations, supply chains, or market access. Focus on: international trade tensions, sanctions regimes, currency fluctuations, regulatory changes in key markets, diplomatic relations affecting business, emerging market instability, commodity price volatility, cross-border investment restrictions, technology transfer policies, and regional conflicts. Consider both risks and opportunities across {company_name}'s geographic footprint and identify any evolving geopolitical narratives that institutional investors and multinational corporations are actively monitoring."""

BUSINESS_AREA_QUESTION_TEMPLATE = """Identify critical industry trends, competitive dynamics, and structural shifts in the {business_area} sector that could materially affect {company_name}'s market position, revenue growth, or profitability. Focus on: emerging technologies disrupting traditional business models, regulatory changes reshaping industry standards, shifting customer preferences and buying behaviors, new market entrants or competitive threats, pricing pressure or margin expansion opportunities, supply chain innovations, consolidation trends, and evolving industry best practices. Prioritize developments that could impact {company_name}'s competitive moat, addressable market size, or operational efficiency within the next 12-24 months."""

MARKET_QUESTION_TEMPLATE = """Investigate recent regulatory policy changes, market structure shifts, and competitive intelligence that could significantly impact {company_name}'s business model, market access, or competitive positioning. Focus on: new legislation or regulatory proposals from relevant government agencies, antitrust investigations or enforcement actions, changes in industry oversight or compliance requirements, competitor strategic moves including acquisitions, partnerships, or market entry/exit decisions, pricing strategies and market share battles, regulatory filings revealing competitor financial health or strategic direction, patent disputes or intellectual property developments, and market concentration trends affecting competitive dynamics. Prioritize developments from the past 3-6 months that could alter {company_name}'s regulatory environment, competitive landscape, or market opportunity set."""

BUSINESS_GROWTH_TEMPLATE = """Identify growth catalysts, strategic initiatives, and value-creation opportunities that could accelerate {company_name}'s revenue expansion, market share gains, or profitability improvements. Focus on: organic growth strategies including new product launches, market expansion into new geographies or customer segments, strategic acquisitions or partnerships that enhance capabilities or market access, capital allocation decisions such as investments in R&D, technology upgrades, or capacity expansion, management changes bringing growth-oriented leadership or operational expertise, digital transformation initiatives improving efficiency or customer experience, strategic divestitures or spin-offs unlocking shareholder value, new business models or revenue streams, and operational improvements driving margin expansion or cost optimization. Evaluate initiatives that could materially impact {company_name}'s growth trajectory, competitive positioning, or long-term value creation potential over the next 18-36 months."""

LEADERSHIP_PERSONNEL_QUESTION = """Investigate recent leadership changes, executive developments, and key personnel movements at {company_name} that could impact strategic direction, operational performance, or investor confidence. Focus on: CEO, CFO, or C-suite executive appointments, departures, or succession planning; board of directors changes including new independent directors or governance updates; key leadership hires in critical business units or emerging growth areas; executive compensation changes or performance incentives; leadership team restructuring or organizational changes; insider trading activity or stock transactions by executives; management commentary during earnings calls or investor events revealing strategic priorities; executive leadership backgrounds and track records that could influence company culture or strategic direction; departures of institutional knowledge holders or domain experts; leadership diversity initiatives or governance improvements; and any management credibility issues, investigations, or controversies that could affect stakeholder trust. Prioritize developments from the past 6-12 months that could influence {company_name}'s execution capabilities, strategic vision, or market perception of leadership effectiveness."""